---
layout: post
title: Java Exceptions 101
created: 2019-05-07 08:23:00 -0800
tags:
- Java
- Exceptions
---
Here are some alternatives titles I could've used:

* "When you think you understand Java&hellip;"
* "Waaaaaa-what? You mean&hellip;"
* "That looks weird."
* "I'm shocked."

Today I'm going to briefly discuss something that tripped me up in my day job the other day. This is perhaps something that every Java developer is taught during the first day on the job or in class but which no one ever remembers until the day it bites them in the behind. Anyway, it's something I didn't know and is really scary. I point you first at the [Java Language Specification][jls] specifically in the section [14.20.2. Execution of `try`-`finally` and `try`-`catch`-`finally`][jls-14.20.2]. I will caution that everything in this section of the document seems completely obvious, but I would like to bring your attention to two specific sentences of this document:

> If the `finally` block completes abruptly for reason `S`, then the `try` statement completes abruptly for reason `S` (and reason `R` is discarded).

and

> **If the `finally` block completes abruptly for reason `S`, then the `try` statement completes abruptly for reason `S` (and the `throw` of value `V` is discarded and forgotten).**

Note that these two sentences are very similar and have similar implications. In the version of the JLS I'm looking at, the second sentence is specifically rendered in bold. I would argue that the first sentence should similarly be rendered in bold for the same reason: this these are both counterintuitive behaviours that can have real-world consequences.

Consider the following pseudo-Java:

{% gist a0c1d8e56ed25bc937935fb4bc1bab89 doOperationRethrowSkipped.java %}

What the referenced section of the Java specification means is that if `action.run()` throws an exception that is assignment-compatible with `Exception` (in the declaration of the `catch` block), the `catch` block will run followed by the `finally` block and, most importantly for our purposes here, _the throw at the end of the `catch` block will be discarded and replaced by the `return true` at the end of the `finally` block_.

Let that sink in for a minute. Go back and re-read that. This may not ring alarm bells in your head at the moment, but you may encountered code like this that assumes that the exception will be rethrown. This is what a percursory glance at the code would suggest. The `return true` is an example of what I'm going to call "action at a distance" and means that, in order to fully understand a `try`-`catch`-`finally` construct in Java, you have to consider how the `finally` block interacts with both your `try` and one or more `catch` blocks, i.e. neither a `try` nor `catch` block in Java is fully self-describing.

The key to interpreting this description of `finally` blocks is to understand what it means for a statement to complete _abruptly_. This is described in detail in the section [14.1. Normal and Abrupt Completion of Statements][[jls-14.1]] in the JLS. This section enumerates all of the _associated reasons_ for an abrupt completion in Java, three of which are most relevant to our example:

> * A `return` with no value
> * A `return` with a given value
> * A `throw` with a given value, including exceptions thrown by the Java Virtual Machine

Thus, in terms of the terminology used in the JLS:

* The `try` block completes abruptly because of a `throw` of value `V` (where `V` is an exception of type `Exception`)
* The `catch` block completes abruptly for reason `R` (`R` being `throw e`)
* The `finally` block completes abruptly for reason `S` (`S` being `return true`)

The overall result, therefore, is that the whole `try` statement completes abruptly with reason `S`, i.e. `return true`, with reason `R`, i.e. `throw e`) being ignored.

The "obvious" behaviour (i.e. the exception is caught and rethrown and the clean-up code in `finally` block is run) can be achieved by rewriting this code as follows:

{% gist a0c1d8e56ed25bc937935fb4bc1bab89 doOperationRethrowNotSkipped.java %}

This following program systematically demonstrates these behaviours:

{% gist a0c1d8e56ed25bc937935fb4bc1bab89 Main.java %}

This program will generate the following output:

{% gist a0c1d8e56ed25bc937935fb4bc1bab89 expected-output.txt %}

So, beware.

## References

* ["Exception Handling&mdash;try catch Java blocks][java-beginners-tutorial] contains the statement _If finally block has a return statement, then the return statements from try/catch blocks will be overridden._: this is correct, though even better would be _f finally block has a return statement, then the last statement from try/catch blocks if it is a return statement or throw statement will be overridden._

[jls]: https://docs.oracle.com/javase/specs/jls/se12/html/index.html
[jls-14.1]: https://docs.oracle.com/javase/specs/jls/se12/html/jls-14.html#jls-14.1
[jls-14.20.2]: https://docs.oracle.com/javase/specs/jls/se12/html/jls-14.html#jls-14.20.2
[java-beginners-tutorial]: https://javabeginnerstutorial.com/core-java-tutorial/exception-handling-try-catch-java/
